### PR TITLE
Fixing Syncthing installation

### PR DESCRIPTION
**Pull request by ghost**
(1) Got an error starting the service because the working directory was empty, is now set to the user path.
(2) Also got an error while starting the service because the config needs a full path.

### CODE REVIEW

**Comment by j8r** [comment]
Thanks for your PR! Little collaterals changes are needed before merging.

**Comment by ghost** [comment]
I know that a different service is being moved from the repo, however my system uses the ones in /etc, and moving the ones of the repo there doesn't work either.

**Comment by j8r** [comment]
Ok no problem we can keep this created service. However, we should do some clean up on the script as commented above on the file.

**Comment by j8r** [comment]
You don't have to use `sed` command, look at the end of `CONTRIBUTING.md`:
```sh
 # Add systemd process and run the server
sh sysutils/services.sh MyApp "/usr/bin/node /usr/bin/MyApp" /home/myapp/MyApp myapp
# This command with its arguments correspond to
# sh ServiceCreationScriptPath ServiceName "ExecStart=" WorkingDirectory= User=
```
Thus we only need to modify the line 60. The last argument that correspond to `User=` isn't needed here.

**Comment by j8r** [comment]
Thanks for you contribution @Datenschutz .

**Pull request merged**
